title: Alexander McDowell's Domain of Mathematics
email: lextmcdowell@gmail.com
description: >-
  This is my blog and portfolio. It contains a small collection of the various mathematical projects and publications I have made.
baseurl: ""
url: "https://alexander-mcdowell.github.io"
github_username: alexander-mcdowell

markdown: kramdown
kramdown:
   math_engine: mathjax

theme: minima
plugins:
  - jekyll-feed

exclude: ['README.md', 'projects/CS114-Final-Project/README.md', 'projects/GraphVisualizer/README.md']